version: '3'

services:
  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.117.24:3379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      sai-im:

  redis:
    image: redis:alpine3.18
    ports:
      - 16379:6379
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      sai-im:
    command: redis-server --requirepass sai-im --appendonly yes

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: sai-im
    restart: always
    networks:
      sai-im:

  mongo:
    image: mongo:4.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sai-im
    ports:
      - 47017:27017
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      sai-im:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      sai-im:

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ws2ms_chat:8:1,ms2ps_chat:8:1,msg_to_mongo:8:1"
      #✨注意：填写的是当前宿主机的ip，即对外能够访问到Kafka的地址
      # 这是因为 ：在go-zero的消息队列组件中，默认监听的是本机的ip，即本机不能访问外网
      KAFKA_ADVERTISED_LISTENERS: INSIDE://192.168.117.24:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    depends_on:
      - zookeeper
    networks:
      sai-im:

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    restart: always
    depends_on:
      - etcd
    volumes:
      - ./components/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      - ./components/apisix-dashboard/schema.json:/usr/local/apisix-dashboard/api/conf/
    ports:
      - "9000:9000"
    networks:
      sai-im:

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    restart: always
    depends_on:
      - etcd
      - apisix-dashboard
    volumes:
      - ./components/apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./components/apisix/logs:/usr/local/apisix/logs
      - ./components/apisix/cert/ssl_PLACE_HOLDER.crt:/usr/local/apisix/conf/cert/ssl_PLACE_HOLDER.crt
      - ./components/apisix/cert/ssl_PLACE_HOLDER.key:/usr/local/apisix/conf/cert/ssl_PLACE_HOLDER.key
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9093:9092/tcp"
    networks:
      sai-im:

  sail:
    image: ccr.ccs.tencentyun.com/hyy-yu/sail:latest
    container_name: sail
    ports:
      - "8108:8108"
    volumes:
      - "./components/sail/compose-cfg.toml:/app/cfg.toml"
    restart: always
    platform: linux/arm64
    networks:
      sai-im:

networks:
  sai-im:
    driver: bridge