scrape_configs:
  - job_name: myapp-test
    #ğŸ”¥é‡‡é›†è¯·æ±‚çš„urlåœ°å€ï¼ˆå› ä¸ºä½¿ç”¨çš„æ˜¯ç›´æ¥é‡‡é›†çš„æ–¹å¼ï¼šåœ¨é¡¹ç›®ä¸­ç¼–å†™ç¨‹åºå¯¹è¦ç›‘æµ‹çš„å®¢æˆ·ç«¯è¿›è¡ŒåŸ‹ç‚¹é‡‡é›†æ•°æ®ï¼‰
    metrics_path: /metrics
    # å…·ä½“è¦è®¿é—®æœåŠ¡çš„åœ°å€
    static_configs:
      - targets:
          - 192.168.117.80:1234